### PR TITLE
Fix BatchCollect limiting the dataset even if skipLimiting is set to true

### LINKED ISSUE #22: Setting skipLimiting to true in BatchCollect.call() does not skip limiting
**Describe the bug**

Setting skipLimiting to true in `call(Dataset<Row> df, Long id, boolean skipLimiting)` actually still applies limits to the dataset.
 
**Expected behavior**

Should not limit the dataset.
 
**How to reproduce**

Use the function with skipLimiting and examine the results.
 
**Screenshots**

 
**Software version**

3.0.0
 
**Desktop (please complete the following information if relevant):**
 - OS: 
 - Browser: 
 - Version: 
 
**Additional context**

### PR DESCRIPTION
**Pull request by 51-code**
Fixes #22.

### CODE REVIEW

File: src/test/java/BatchCollectTest.java [hunk 1]
```diff
@@ -88,8 +88,9 @@ public class BatchCollectTest {
             }
     );
 
-    //@Test
-    public void testCollect() throws StreamingQueryException, InterruptedException {
+    @Test
+    @Disabled
```
Comment (StrongestNumber9) [inline src/test/java/BatchCollectTest.java:92]: Why is this test disabled? Add a reason like `@Disabled(value="Broken component xyz")`

Comment (51-code) [reply src/test/java/BatchCollectTest.java]: Looked into it, it was testing the `getCollected()` method, but failing unexpectedly because of how the test data was created in that test. However there was a "TODO: remove" on the function so I just got rid of the method and the test as well. The method wasn't used anywhere in PTH-10 so it was safe to do so. Fixed some other stuff in tests at the same time and added more assertions.

**Review by eemhu — APPROVED** [review]

**Review by kortemik — APPROVED** [review]
